# configs do spring data
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

## contexto da aplicacao
server:
  port: 7075
  servlet.contextPath: /case-star-wars
  