apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: case-star-wars
spec:
  selector:
    matchLabels:
      app: case-star-wars
  replicas: 3
  template:
    metadata:
      labels:
        app: case-star-wars
    spec:
      containers:
      - name: case-star-wars-container
        image: rafakiyota/case-star-wars:latest
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
        env:
        - name: GET_HOSTS_FROM
          #value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          value: env
        ports:
        - containerPort: 7075