apiVersion: v1
kind: Service
metadata:
  name: case-star-wars
  labels:
    app: case-star-wars
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  # type: NodePort 
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 7070
    targetPort: 7075
  selector:
    app: case-star-wars